version: '3.4'

services:
  catalogDb:
   container_name: catalogdb
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=01018903943
    - POSTGRES_DB =CatalogDB
   restart: always
   ports:
    - "5432:5432"
   volumes:
    - postgres_catalog:/var/lib/postgresql/data/ 